#!/bin/bash


fct() {
	printf "Testing $1: "
	`./corewar -d $2 ./_cor/$1 > ./_out/$1` 2> error
	DIFF=`diff ./_out/$1 ./_zaz_output/$1`
	ERROR=`cat error`
	if [ "$DIFF" = "" ]
	then
		printf "\033[0;32m[OK]\033[0;0m\n"
	elif [ "$ERROR" != "" ]
	then
		printf "\033[0;31m[KO: `cat error`]\033[0;0m\n"
	else
		printf "\033[0;31m[KO]\033[0;0m\n"
	fi
}

make re
mkdir _out 2> /dev/null
clear
source ./core_test.sh
echo "If you got errors, your outputs is in the folder _out and zaz's outputs is in _zaz_output folder."
