#!/bin/sh


fct() {
	echo "Testing $1: \c"
	`./corewar -d $2 ./_cor/$1 > ./_out/$1` 2> error
	DIFF=`diff ./_out/$1 ./_zaz_output/$1`
	ERROR=`cat error`
	if [ "$DIFF" = "" ]
	then
		echo "\033[32m[OK]\033[0m"
	elif [ "$ERROR" != "" ]
	then
		echo "\033[31m[KO: `cat error`]\033[0m"
	else
		echo "\033[31m[KO]\033[0m"
	fi
}

make re
mkdir _out 2> /dev/null
clear
source ./core_test.sh
echo "If you got errors, your outputs is in the folder _out and zaz's outputs is in _zaz_output folder."
