#!/bin/bash

exec 2> error

fct() {
	echo -e "Testing $1: \c"
	./corewar -d $2 ./_cor/$1 > ./_out/$1
	DIFF=`diff ./_out/$1 ./_zaz_output/$1`
	ERROR=`cat error`
	if [ "$DIFF" = "" ]
	then
		echo -e "\033[0;32m[OK]\033[0;0m"
	elif [ "$ERROR" != "" ]
	then
		echo -e "\033[0;31m[KO: `cat error`]\033[0;0m"
	else
		echo -e "\033[0;31m[KO]\033[0;0m"
	fi
}

make re
mkdir _out 2> /dev/null
clear
source ./dump_tests
echo "If you got errors, your outputs is in the folder _out and zaz's outputs is in _zaz_output folder."
rm error
